### ISSUE TITLE
Seeing JS error in my browser

### ISSUE THREAD

**Issue by ovizii** [postmatic/epoch#121] opened 2015-10-06 09:45 UTC
Uncaught Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined

http://foodandchatter.co.za/wp-content/plugins/epoch//assets/js/front/handlebars.js?ver=1443543314

**Comment by shackep** [comment] 2015-10-07 12:45
@ovizii, are you using a caching plugin or something that could be getting all the js files and minifying them?

**Comment by ovizii** [comment] 2015-10-07 18:37
Thanks for replying.
Yes I'm running ngx_pagespeed on this server (that is the pagespeed module for nginx) 
I can setup exceptions, is it necessary to make an exception and for which files?

**Comment by shackep** [comment] 2015-10-08 14:04
I am not sure. I am just another user. I wanted to help you isolate the cause so you could try a few things.

**Comment by Vernal** [comment] 2015-10-08 15:04
Thanks guys for reporting this. I'll have someone look at it during our next round of development and keep you updated here.

**Comment by mihche** [comment] 2015-10-19 19:39
Epoch loads and localize scripts. 

``` javascript
var epoch_vars = {"api_url":"http:\/\/blablabla.com\/epoch-api","submit_api_url":"http:\/\/blablabla.com\/epoch-api?epochNonce=e6d62e69ff&action=submit_comment","depth":"5","nonce":"e6d62e69ff","live_mode":"1","wrap_class":"epoch-wrapper","count_id":"epoch-count","wrap_id":"epoch-wrap","form_wrap":"epoch-commenting","form_id":"commentform","submit_id":"epoch-submit","comments_wrap":"epoch-comments","comments_template_id":"epoch-comment-template","nonce_field":"epochNonce","endpoint":"epoch-api","reply_link_id":"epoch-reply-link","sniffer":"epoch-width-sniffer","epoch_options":{"theme":"light","threaded":false,"before_text":"Epoch Test Mihai","interval":182000,"order":"ASC"},"post_id":"1"};
```

So... you have in `epoch_vars` object: 
`"comments_template_id":"epoch-comment-template"`

In epoch.js, in app.init you have:
`app.template_el = document.getElementById( epoch_vars.comments_template_id );`

``` javascript
app.parse_comment = function( comment ) {
    parent_id = comment.comment_parent;
    source = $( app.template_el ).html();
    template = Handlebars.compile( source );
    html = template( comment );
    return html;
}; 
```

When you pass source to Handlebars.compile, you'll pass undefined because the page does NOT have the template rendered.
That's why you are getting **"You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined"**

Now let's see why the template is not rendered. Let's go to your main class in core.php file
`add_action( 'parse_query', array( $this, 'boot_epoch_front' ) );`

``` php
public function boot_epoch_front( $query ) {
   if ( false !== $query->is_singular ) {
      $options = options::get_display_options();
      if ( 'none' == $options[ 'theme' ] ) {
         vars::$wrap_id = 'comments';
      }

      //add_action( 'wp_enqueue_scripts', array( $this, 'front_stylescripts' ) );
      add_filter( 'comments_template', array( '\postmatic\epoch\front\layout', 'initial' ), 100 );
      add_action( 'epoch_iframe_footer', array( $this, 'print_template' ), 9 );
      add_action( 'wp_footer', array( $this, 'print_template' ) );
      add_filter( 'the_content', array( '\postmatic\epoch\front\layout', 'width_sniffer' ), 100 );

   }

}
```

In `boot_epoch_front` function you guys are adding the `wp_footer` action, which prints the template ONLY if `false !== $query->is_singular` is satisfied. On the front page or others this condition is not always satisfied. If you take out the

```
add_action( 'wp_footer', array( $this, 'print_template' ) ); 
```

and put it outside of that IF condition the problem should be solved. Also, this can be easily solved from javascript. 

If you can't replicate this just debug WPTavern home page and you'll see it in action

Mihai

**Comment by Vernal** [comment] 2015-10-20 14:01
Thanks for the great breakdown, Mihai. We are gearing up for another code sprint this week or next and resolution for this will be in there. @Shelob9 be sure to give this some attention.

Jason

**Comment by Shelob9** [comment] 2015-10-24 01:09
@mihche In 761aeb4 I changed how we determine if Epoch front-end is needed -- loading only if current post has comments or comments are open. In the future we can do more with that, such as shutting down polling if comments are not loaded.

The other part of the problem was that the method that was loading the template for the iframe was running the enqueue method no matter what. That is fixed in 2cb30b7

**Closed as completed by Shelob9** 2015-10-24 01:09 UTC
Labels: bug

**Comment by ovizii** [comment] 2015-10-24 18:57
Awesome, thanks everyone!

**Comment by Vernal** [comment] 2015-10-24 19:11
Yay! We will ship 1.0.8 on Monday. 

Jason
